config/routes.rb
Netball::Application.routes.draw do
  resources :players do
    member do
      get 'schedule'
      post 'scheduled'
    end
  end
  
  resources :fixtures do
    member do
      post 'cancel'
      post 'uncancel'
    end
  end
  
  match 'overview' => 'overview#index'
  
  root :to => 'overview#index'
  

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  YES = 'Yes'
  NO = 'No'
  UNSURE = 'Unsure'
  WILL_OPTIONS = %w(YES, NO, UNSURE)
  
  belongs_to :fixture
  belongs_to :player
  
  validates :will, :inclusion => { :in => [YES, NO, UNSURE] }
end

app/models/fixture.rb
class Fixture < ActiveRecord::Base
  has_many :attendances
  has_many :players, :through => :attendances

  validates :title, :presence => true,
                    :length => { :minimum => 2, :maximum => 50 }
  validates :date, :presence => true
  
  default_scope :order => 'date ASC'
  
  def self.all_upcoming
    where("date >= ?", Date.today())
  end
  
  def to_s
    title + ', ' + date.to_s(:table)
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :attendances
  has_many :fixtures, :through => :attendances
  
  validates :name, :presence => true,
                    :length => { :minimum => 2, :maximum => 30 }

  default_scope :order => 'name ASC'
              
  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/attendance_controller.rb
class AttendanceController < ApplicationController
end

app/controllers/fixtures_controller.rb
class FixturesController < ApplicationController
  # GET /fixtures/new
  def new
    @fixture = Fixture.new
    @fixture.title = 'Training'
  end

  # GET /fixtures/1/edit
  def edit
    @fixture = Fixture.find(params[:id])
  end

  # POST /fixtures
  def create
    @fixture = Fixture.new(params[:fixture])

    if @fixture.save
      redirect_to '/', notice: 'Fixture was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /fixtures/1
  def update
    @fixture = Fixture.find(params[:id])

    if @fixture.update_attributes(params[:fixture])
      redirect_to '/', notice: 'Fixture was successfully updated.'
    else
      render action: "edit"
    end
  end

  def cancel
    @fixture = Fixture.find(params[:id])

    if @fixture.update_attributes(:cancelled => true)
      redirect_to '/', notice: 'Fixture has been cancelled.'
    else
      redirect_to '/', notice: 'Error cancelling fixture.'
    end
  end
  
  def uncancel
    @fixture = Fixture.find(params[:id])

    if @fixture.update_attributes(:cancelled => false)
      redirect_to '/', notice: 'Fixture has been uncancelled.'
    else
      redirect_to '/', notice: 'Error uncancelling fixture.'
    end
  end

  # DELETE /fixtures/1
  def destroy
    @fixture = Fixture.find(params[:id])
    @fixture.destroy

    redirect_to '/'
  end
end

app/controllers/overview_controller.rb
class OverviewController < ApplicationController
  def index
    @fixtures = Fixture.all_upcoming
    @players = Player.all
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  def index
    @players = Player.all
  end

  def schedule
    @player = Player.find(params[:id])
    @fixtures = Fixture.all_upcoming
  end

  # POST
  def scheduled
    @player = Player.find(params[:id])
    params[:fixtures].each { |fixture_id, will|
      attendances = Attendance.where('player_id = ? AND fixture_id = ?', @player.id, fixture_id)
    
      if attendances.empty?
        attendance = Attendance.new({:player_id => @player.id, :fixture_id => fixture_id})
      else
        attendance = attendances[0]
      end
      attendance.will = will
      attendance.save!
    }
  
    redirect_to '/', notice: 'Schedule saved.'
  end

  # GET /players/1
  def show
    @player = Player.find(params[:id])
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  def create
    @player = Player.new(params[:player])

    if @player.save
      redirect_to '/', notice: 'Player was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /players/1
  def update
    @player = Player.find(params[:id])

    if @player.update_attributes(params[:player])
      redirect_to '/', notice: 'Player was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /players/1
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/helpers/overview_helper.rb
module OverviewHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/fixtures/_form.html.erb
<%= form_for(@fixture) do |f| %>
  <% if @fixture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fixture.errors.count, "error") %> prohibited this fixture from being saved:</h2>

      <ul>
      <% @fixture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fixtures/edit.html.erb
<h1>Editing fixture</h1>

<%= render 'form' %>

<div id="admin">
  <%= form_tag(:action => @fixture.cancelled ? "uncancel" : "cancel") do -%>
  <%= hidden_field_tag(:id, @fixture.id) %>
    <div class="actions">
      <input type="submit" value="<%= @fixture.cancelled ? 'Uncancel' : 'Cancel' %> fixture"/>
    </div>
  <% end -%>  
  <%= link_to 'Back', '/' %>
</div>

app/views/fixtures/new.html.erb
<h1>New fixture</h1>

<%= render 'form' %>

<%= link_to 'Back', '/' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Netball</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Crafty+Girls' rel='stylesheet' type='text/css'>
</head>
<body>
  <div id="page">
    <div id="header">
      <a href="/"><%= image_tag("netball-shot.jpg", :id => "logo", :alt => "Netball shot logo") %></a>
      <a href="/"><%= image_tag("valencia-netball.png", :id => "title", :alt => "Valencia Netball") %></a>
    </div>
    
    <div id="content">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/overview/index.html.erb
<h1>Valencian Netball Team Schedule</h1>

<table>
  <tr>
    <th></th>
    <% @fixtures.each do |fixture| %>
    <th <% if fixture.cancelled? %>class="cancelled"<% end %>><%= link_to fixture.to_s, edit_fixture_path(fixture) %></th>
    <% end %>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= link_to player.name, schedule_player_path(player) %></td>
    <% @fixtures.each do |fixture| %>
      <% if fixture.cancelled? %>
        <td class="cancelled">Cancelled
      <% else %>
        <% attendances = player.attendances.where("fixture_id = ?", fixture.id)
        if attendances.empty? %>
          <td class="unsure">Unsure
        <% else %>
        <td class="<%= attendances[0].will.downcase %>"><%= attendances[0].will %>
        <% end %>
      <% end %>
    </td>
    <% end %>
  </tr>
<% end %>
<tr>
  <td>Total</td>
  <% @fixtures.each do |fixture| %>
  <td><%= fixture.attendances.where('will = ?', 'Yes').count %></td>
  <% end %>
</tr>
</table>
<p>Click on a player's name to modify her schedule.</p>
<div id="admin">
  <p><%= link_to 'New Player', new_player_path %> <%= link_to 'New Fixture', new_fixture_path %></p>
</div>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Back', '/' %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', '/' %>

app/views/players/schedule.html.erb
<h1>Modify Schedule for <%= @player %></h1>

<%= form_tag(:action => "scheduled") do -%>
  <%= hidden_field_tag(:id, @player.id) %>
  
  <% @fixtures.each do |fixture| %>
    <% attendances = @player.attendances.where("fixture_id = ?", fixture.id)
    if attendances.empty?
      will = 'Unsure'
    else
      will = attendances[0].will
    end
  %>
    <div class="field">
      <p><%= fixture.to_s %><%= fixture.cancelled ? ' (cancelled)' : '' %><br/>
      <%= select_tag("fixtures[#{fixture.id}]", options_for_select(['Yes', 'No', 'Unsure'], will)) %></p>
    </div>
  <% end %>
  <div class="actions">
    <input type="submit" value="Save schedule"/>
  </div>
<% end -%>

<div id="admin">
  <%= link_to 'Back', '/' %>
  <%= link_to 'Change name', edit_player_path(@player) %>
  <%= link_to 'Delete player', @player, confirm: 'Are you sure?', method: :delete %>
</div>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @player.name %>
</p>


<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>